### ISSUE TITLE
Yoast AMP Broken Site After Feature Image Add

### ISSUE THREAD

**Issue by DanielCryptoK** [Yoast/yoastseo-amp#107]
Hi,

I have just added logo and feature image to the Yoast AMP option which has now broken my site.

All of the pages such as my category and tag pages which do not have a feature image are now showing a 404 error.

I have tried to remove the images added in yoast AMP but the clear button has stopped working so I am unable to fix the issue.

How do I remove the images added to Yoast AMP when the clear button has stopped?

I have AMP plugin also installed along with Glue for yoast.

Please see attached images for examples
![amp - yoast seo bitcoin casino no deposit bonus wordpress](https://user-images.githubusercontent.com/45933242/50073962-4aba6400-01d2-11e9-82b7-9ce0990890e8.png)
![404 page bitcoin casino no deposit bonus](https://user-images.githubusercontent.com/45933242/50073986-5c9c0700-01d2-11e9-8e39-bfc947b95ff5.png)

**Comment by benvaassen** [comment]
Hi @DanielCryptoK, thanks for reporting this issue! The clear button is definitely broken, so we'll have to fix that. However, the AMP tag and category pages work for me as expected. 

If you disable the Glue for Yoast SEO & AMP plugin, do the AMP tag and category pages work? If they do, can you show me your steps to reproduce the 404 pages?

**Comment by moorscode** [comment]
Until we have fixed this problem, you can use the following JavaScript command in the console:
```
jQuery('input[name="wpseo_amp[amp_site_icon]"]').val('');
jQuery('input[name="wpseo_amp[amp_site_icon_id]"]').val('');
```

You can open the console by right-clicking on an element in the page and select 'inspect' and click on the `console`-tab or use:

Chrome + MacOS: `command`+`option`+`J`
Chrome + Windows: `control`+`shift`+`J` 

Firefox + MacOS: `command`+`option`+`K`
Firefox + Windows: `control`+`shift`+`K`

Paste the lines and press enter to execute them, the field should be cleared.
Press "Save" to save the changes.

**Comment by DanielCryptoK** [comment]
I have tried every single option and no matter what I do I still get a 404 error for the category and tag amp pages. I have tried AMP plugin only, AMP plugin + Yoast, Yoast Only, Yoast and Yoast Glue, AMP Plugin and Yoast Glue but all result in a 404.

**Comment by benvaassen** [comment]
@DanielCryptoK If you have the 404 issue when you've disabled the Glue for Yoast SEO & AMP plugin, then it's not something we can fix in our plugin. It might be a setting in the AMP plugin or some form of caching that's causing this. Also, sometimes resaving your permalinks can work.

**Comment by DanielCryptoK** [comment]
what about creating a 301 redirect to the correct AMP page?
